#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke
tmpfile=$(mktemp $HOME/.XXXXXX.tmp)
# trap 'rm "$tmpfile"' 0 1 15
echo $tmpfile
cat > $tmpfile
# sed -i 's/\x0//g' "$tmpfile"
cat $tmpfile
# echo "grep results"
ps1rgx="^~/.*: \|^/.*: "
grep -h "$ps1rgx" "$tmpfile"
# look for prompt string, delete last line, reverse order, pipe into dmenu
chosen=$( grep "$ps1rgx" "$tmpfile" | sed '$ d' | tac | dmenu | sed 's/[^^]/[&]/g; s/\^/\\^/g' )
# # # cat $tmpfile | grep "^[\/,~](\/.*)*: "
# chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
eps1rgx="^~\/.*: |^\/.*: "
echo "chosen: $chosen"
echo "eps1rgx: $eps1rgx"
# echo "eps1rgx: $eps1rgx" | dmenu
awk "/^$chosen$/{p=1;print;next} p&&/$eps1rgx/{exit 0};p" "$tmpfile" | xclip -selection clipboard
