#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke
tmpfile=$(mktemp $HOME/.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
sed -i 's/\x0//g' "$tmpfile"
cat $tmpfile
echo "grep results"
cat $tmpfile | grep "^[\/,~](\/.*)*: "
# chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
# echo "chosen: $chosen"
# eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
# echo "eps1: $eps1"
# awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
