#!/bin/sh
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX.term)
# cat $tmpfile
trap 'rm "$tmpfile"' 0 1 15
cat $tmpfile
cat > "$tmpfile"
# cat $tmpfile
sed -i 's/\x0//g' "$tmpfile"
# cat $tmpfile
echo $EDITOR
# st -e "nvim" "$tmpfile"
devour st -e nvim -c 'norm GggG' "$tmpfile"

# nvim "$tmpfile"
# cat $tmpfile
# echo $tmpfile
# exit 1
# ps1="$(grep "\S" "$tmpfile" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
# chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | dmenu -p "Copy which command's output?" -l 10 | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
# eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
# awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
